version: '3.8'

services:
  openmodelica-gui:
    #build: 
    #  context: .
    #  dockerfile: ./docker/tricys_om_gui.dockerfile

    image: ghcr.io/asipp-neutronics/tricys_openmodelica_gui:develop
    #image: tricys_openmodelica_gui

    # 从运行 docker-compose 的 shell 中获取 DISPLAY 变量的值
    environment:
      - DISPLAY=${DISPLAY}
      - PATH=/home/appuser/.local/bin:${PATH}

    # 用于挂载 X11 的 socket，让GUI可以通信
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${CUSTOM_MODEL_PATH}:/tricys/model

    # 保持容器在前台交互运行
    #stdin_open: true
    #tty: true

    # 定义容器启动后要执行的命令
    command: OMEdit